FROM python:3.11.0
ENV PYTHONUNBUFFERED 1
RUN pip install --upgrade pip
RUN pip install fastapi
RUN pip install "uvicorn[standard]"
RUN pip install fastapi_csrf_protect
RUN pip install motor
RUN pip install PyJWT
RUN pip install passlib
RUN pip install python-decouple
RUN pip install dnspython
RUN pip install gunicorn
RUN pip install bcrypt

